version: '3.3'
services:
  ycast:
    #image: arcao/ycast-docker
    build: .
    container_name: ycast
    restart: on-failure:5
    # Set your hostname to the FQDN under which your
    # sattelites will reach this container
    hostname: ycast
    volumes:
      - ./data/stations.yaml:/opt/ycast/stations.yml
    labels:
      - traefik.enable=true
      - traefik.http.services.ycast.loadbalancer.server.port=80
      - traefik.http.services.ycast.loadbalancer.server.scheme=http
      - traefik.http.routers.ycast.rule=Host(`radioyamaha.vtuner.com`, `radioyamaha2.vtuner.com`)
      - traefik.http.routers.ycast.entrypoints=web
